//package java17RecordClasses;
//
//import java.math.BigDecimal;
//
//public record Product(
//        String name,
//        BigDecimal cost,
//        String type
//) {
//
//    /*
//    By default constructor generated by the complier that is called canonical constructor
//     */
//
//    public Product() {
//
//        // let's do some validation
//
//        if (name != null && name.isBlank()) {
//            throw new IllegalArgumentException("Name is not valid");
//        }
//
//        if (cost.compareTo(BigDecimal.ZERO) <= 0) {
//            throw new IllegalArgumentException("Cost should be greater than 0");
//        }
//
//
//    }
//}


package java17RecordClasses;

import java.math.BigDecimal;

public record Product(
        String name,
        BigDecimal cost,
        String type
) {

    // Compact Canonical Constructor
    public Product {

        if (name != null && name.isBlank()) {
            throw new IllegalArgumentException("Name is not valid");
        }

        if (cost == null || cost.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Cost should be greater than 0");
        }
    }
}
